"""empty message

Revision ID: 92806601ea6f
Revises: ffd5938597e1
Create Date: 2022-06-02 17:45:06.950408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92806601ea6f'
down_revision = 'ffd5938597e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('genres', sa.ARRAY(sa.String()), nullable=False))
    op.add_column('venue', sa.Column('genres', sa.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'genres')
    op.drop_column('artist', 'genres')
    # ### end Alembic commands ###
